name: Check licenses

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check licenses
        uses: ory/ci/licenses/setup@master
        with:
          token: ${{ secrets.ORY_BOT_PAT || secrets.GITHUB_TOKEN }}
      - name: Check licenses
        uses: ory/ci/licenses/check@master
        with:
          token: ${{ secrets.ORY_BOT_PAT || secrets.GITHUB_TOKEN }}

      - name: Check licenses
        uses: ory/ci/licenses/check@master
        with:
          token: ${{ secrets.ORY_BOT_PAT || secrets.GITHUB_TOKEN }}
