name: Check licenses

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check licenses
        uses: ory/ci/check-licenses@master
        with:
          token: ${{ secrets.ORY_BOT_PAT || secrets.GITHUB_TOKEN }}
          write_if_match: ${{ github.ref == 'refs/heads/add-license-check' || github.ref == 'refs/heads/main' }}
